### ISSUE TITLE
SSL Example

### ISSUE THREAD

**Issue by nickste** [srigaurav1986/KurentoExample#2]
Hi there,

Chrome now requires WebRTC to use SSL in order to share camera, mic, etc. The only way to run this example at the moment is on localhost.

Would it be possible for you to provide a version that supports SSL?

**Comment by gaurav-payoda** [comment]
I think localhost is hardcodced in server.js , Please change the url to wss in server.js
ie 
const ws_uri = "ws://localhost:8888/kurento"; to const ws_uri = "wss://a.b.c.d:8888/kurento"; 
where a.b.c.d is you kms ip.

Unfortunately I don't have the ubuntu setup else I would have given the tested result.

**Comment by srigaurav1986** [comment]
I think localhost is hardcodced in server.js , Please change the url to wss in server.js ie
 const ws_uri = "ws://localhost:8888/kurento"; to const ws_uri = "wss://a.b.c.d:8888/kurento"

Unfortunately I don't have the ubuntu setup else I would have given the tested solution.
Please let me know in case of any concern.

**Comment by casualuser** [comment]
just for keeping info updated:

here is exists updated fork of this demo with enabled ssl - https://github.com/gerardcl/KurentoExample
