### ISSUE TITLE
Failed at the kurento-composite-call@6.1.1-dev start script 'node serve

### ISSUE THREAD

**Issue by bogere** [srigaurav1986/KurentoExample#3]
Hullo, thank you for your great web app.
at first i was it was able to run with 3 connected users..
but currently it is failing when i try to add the second person.... the app just crashes...in the node process.
these are errors i get.
argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! kurento-composite-call@6.1.1-dev start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the kurento-composite-call@6.1.1-dev start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kurento-composite-call package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kurento-composite-call
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kurento-composite-call
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/goldsoft25/Desktop/NodeJS/kurento-tutorial-node-master/KurentoExample/npm-debug.log

**Comment by srigaurav1986** [comment]
Sorry for a late reply. I hope you would have recognize that there are some promise missing between candidate gathering and creating answer. This was a prototype lightweight program written make things in tune for then latest version on Kurento.
